name: Build

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Job 2
        run: echo "Job 2 is running after Job 1!"
